#!/usr/bin/env bash
spotify=/usr/bin/spotify
blocker=$HOME/blockSpotifyAds.sh
if [[ -x $spotify && -x $blocker ]];
then
  $blocker &
  block_pid=$!
  echo "Blocker: $block_pid" > /tmp/spotifyWrapper.$$
  echo "Spotify wrapper: $$" >> /tmp/spotifyWrapper.$$
  $spotify
  # shellcheck disable=SC2064
  trap "kill -TERM $block_pid" SIGINT SIGTERM EXIT
fi
