#!/usr/bin/env bash
declare -A map
eval "$(command connmanctl services | \
  awk 'NF > 1 { print "map["$(NF - 1)"]="$NF; next }
              { print "map["$NF"]="$NF }')"
i=0
declare -a args
for arg in "$@"; do
  [[ "${map[$arg]}" ]] && args[i++]="${map[$arg]}" || args[i++]="$arg"
done
command connmanctl "${args[@]}"
